### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by blechturm** [koenderks/jfa#199]
**Describe the bug**
This might be a bug but maybe it is in reality a question about the behaviour of the planning algorithm with the hypergeometric distribution and how to interpret the results.

My issue is that I do not know the size of my population yet (the urn is not filled up with balls yet so to speak). So I tried to get a feeling about the needed sample sizes with different settings. 

I would expect the sample size to growh monotonically with the population size. But this is not the case if I try the planning algorithm with a hypergeometric distribution iteratively with growing population sizes.

**To Reproduce**

Heres a script that demonstrates my issue/question

```
library(tidyverse)
library(jfa)

ar          <- 0.05 # Audit risk
materiality <- 0.05 # Performance materiality
expected    <- 0.01 # Tolerable deviation rate

ir <- 1              # Inherent risk
cr <- 0.6            # Control risk
dr <- ar / (ir * cr) # Detection risk
dr

test1 <- tibble(population_size = seq(50, 5000, by= 50)) %>%
  mutate(n = map(population_size, ~planning(materiality = 0.05, 
                                    expected = 0.02, 
                                    conf.level = 0.95, 
                                    by = 10,
                                    likelihood = "hypergeometric",
                                    N.units = .x,
                                    max = 5000))) %>%
  mutate(sample_size_needed = map(n, ~pluck(.x, "n"))) %>%
  unnest(sample_size_needed) %>%
  mutate(sample_size_percentage = sample_size_needed/population_size) %>%
  select(-n) %>%
  mutate(settings = "Mat 0.05, Expected 0.02, Conf 0.95")


test2 <- tibble(population_size = seq(50, 5000, by= 50)) %>%
  mutate(n = map(population_size, ~planning(materiality = 0.05, 
                                    expected = 0.02, 
                                    conf.level = 1- dr, 
                                    by = 10,
                                    likelihood = "hypergeometric",
                                    N.units = .x,
                                    max = 5000))) %>%
  mutate(sample_size_needed = map(n, ~pluck(.x, "n"))) %>%
  unnest(sample_size_needed) %>%
  mutate(sample_size_percentage = sample_size_needed/population_size) %>%
  select(-n) %>%
  mutate(settings = paste0("Mat 0.05, Expected 0.02, Conf ",round(1-dr, 2)))



test3 <- tibble(population_size = seq(50, 5000, by= 50)) %>%
  mutate(n = map(population_size, ~planning(materiality = 0.10, 
                                            expected = 0.05, 
                                            conf.level = 0.95,
                                            by = 10,
                                            likelihood = "hypergeometric",
                                            N.units = .x,
                                    max = 5000))) %>%
  mutate(sample_size_needed = map(n, ~pluck(.x, "n"))) %>%
  unnest(sample_size_needed) %>%
  mutate(sample_size_percentage = sample_size_needed/population_size) %>%
  select(-n) %>%
  mutate(settings = "Mat 0.10, Expected 0.05, Conf 0.95")


bind_rows(test1,
          test2,
          test3) %>%
  ggplot() +
  aes(x= population_size,
      y= sample_size_needed,
      color = settings,
      group = settings) %>%
  geom_line() +
  theme_minimal() +
  labs(title = "Comparison of Settings")
```

**Expected behavior**

I would expect that the sample size increases monotonically with a given set of settings but increasing N.units. But there are weird spikes if I try this (as seen as in the code above)

**Screenshots**

See the ggplot output in the code, it demonstrates the issue.

**Comment by koenderks** [comment]
Hi!

In general, as the population size `N.units` increases, the required sample size `n` also increases to maintain a desired level of confidence. However, the relationship between `N` and `n` is not necessarily monotonic, and there can be "spikes" or non-monotonic behaviour in some cases. I think this is because for the expected errors in the population `K` we use `ceiling(expected * N.units)`, which is conservative and means that we round even numbers as 1.001 to 2.

To verify, let's focus on these outputs to illustrate this (`materiality = 0.05, expected = 0.02, conf_level = 0.95`):

population_size | sample_size_needed
| -- | -- |
| 2650 | 150 | 
| 2700 | 180 |
| 2750 | 150 |
| 2800 | 180 | 
| 2850 | 150 | 
| 2900 | 180 | 
| 2950 | 150 | 
| 3000 | 180 | 
| 3050 | 150 |
| 3100 | 180 | 
| 3150 | 150 | 
| 3200 | 180 |
| 3250 | 180 |  

You can check the correctness for all these outputs using the following code:

```
audit_risk <- 1 - 0.95
materiality <- 0.05
N <- 2650
n <- 150
expected <- ceiling(0.02 * n)
K <- ceiling(materiality * N)
sum(dhyper(x = 0:expected, m = K, n = N - K, k = n)) < audit_risk # TRUE
```

Hope this helps. If you still feel like this is a bug, feel free to reopen this issue!
